<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel_link"/>
        <origin xyz="${0.25 - wheel_radius*2} ${-0.25- wheel_length/2} -0.10" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="10" velocity="0.1"/>
    </joint>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel_link"/>
        <origin xyz="${0.25 - wheel_radius*2} ${0.25+ wheel_length/2} -0.10" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
        <limit effort="10" velocity="0.1"/>
    </joint>

    <joint name="castor_joint" type="fixed">
        <parent link="base_link"/>
        <child link="castor_wheel_link"/>
        <origin xyz="-0.2 0 -0.15" rpy="0 0 0"/>
    </joint>

</robot>